### ISSUE TITLE
Cómo organizar el tiempo del usuario

### ISSUE THREAD

**Issue by raultl12** [carlotiii30/organizacionSemanal#12]
Según la historia #2, se genera el problema de cómo organizar el tiempo del usuario para que pueda optimizar la realización de sus actividades. Esta representación es vital para que en #15 se pueda hacer la optimización del tiempo.

**Comment by JJ** [comment]
Estás sugiriendo una solución, *representar* *el tiempo*. Está claro que hay que organizar el tiempo, pero qué se represente y por qué dependerá del resto de la lógica de negocio, no tienes que asumir algo determinado.

**Comment by JJ** [comment]
¿No crees que el problema sería más bien cómo *organizar* el tiempo? A partir de ahí la solución puede ser representarlo, pero también puede haber otra...
