### ISSUE TITLE
Cómo representar una actividad

### ISSUE THREAD

**Issue by raultl12** [carlotiii30/organizacionSemanal#13]
El issue #12 presenta el concepto de actividad, pero, ¿Qué es una actividad?

Una actividad es una tarea que debe realizar el usuario un dia determinado a una hora determinada. El problema que surge aquí es: ¿Cómo representamos una tarea para que pueda ser optimizada junto a todas las demás?

**Comment by JJ** [comment]
¿Te parece que esto es un enunciado de un problema? ¿O directamente dice cuál es la solución, sin decir cuál es el problema?
Trabajar también con issues en cascada tiene cierto peligro, porque si uno de los issues que está ahí se "cae", el resto tampoco vana poder hacerse.

**Comment by JJ** [comment]
¿Siempre se tiene que hacer a una hora determinada? Que me corrija @carlotiii30 si me equivoco, pero me da la impresión de que hay tareas como las citas médicas que sí, y otras como hacer ejercicio que quizás tengan otro tipo de requisitos, ¿no?

**Comment by JJ** [comment]
El enfocar los objetivos en un solo objeto en vez de en problemas hace que no se puedan resolver correctamente según DDD. 
En este caso, el problema no es cómo representar *una* actividad, sino cómo gestionar actividades. Hay una parte de la gestión de la actividad que está bien resuelta (si son aplazables, por ejemplo, aunque habría que ver qué implica esto en sus campos `Tarea` y `Date`) pero no cómo tener en cuenta si una actividad ha sido realizada o no. 
Por otro lado, si la actividad, o algún tipo, puede ser aplazable (lo que tendría que solucionarse por el tipo de actividad) la fecha también es mutable, por lo que también tendría que expresar ese problema aquí para que se gestione desde otro tipo de entidad.
