### ISSUE TITLE
[HU01] Estudiante despistada

### ISSUE THREAD

**Issue by carlotiii30** [carlotiii30/organizacionSemanal#2]
Como estudiante del doble grado de Ciencias de la Actividad Física y del Deporte y Nutrición Humana y Dietética, estoy muy comprometida con el deporte y el bienestar de las personas, sobretodo, de mi persona. Quiero una forma de optimizar mi tiempo para poder equilibrar mis estudios, el ejercicio físico y las citas médicas sin sentirme abrumada.

**Comment by JJ** [comment]
¿Te parece que la frase que empieza en "además" representa, por un lado, algo que se pueda hacer con la lógica de negocio y, por otro lado, algo que esté en el dominio del problema? Si lo estuviera, ¿te parece que forma parte de esta misma HU o podría ser una diferente?
