### ISSUE TITLE
Lenguaje de programación

### ISSUE THREAD

**Issue by raultl12** [carlotiii30/organizacionSemanal#4]
Hola, me ha tocado trabajar con este repositorio para el objetivo 2. Lo primero que tenemos que hacer es decidir el lenguaje de programación que se va a usar. Mis propuestas son: Python, JavaScript, Go y Typescript.

**Comment by raultl12** [comment]
Entre esas dos, creo que es mejor Typescript, por su tipado estático, su semejanza a javascript y por que se puede usar tanto para back-end como front-end. Si te parece bien, usamos Typescript.

**Comment by carlotiii30** [comment]
Typescript entonces, perfecto
