### ISSUE TITLE
Notificaciones

### ISSUE THREAD

**Issue by raultl12** [carlotiii30/organizacionSemanal#8]
Para resolver #2 se debe encontrar una forma para representar una notificación, además de determinar los elementos que la componen. Una notificación es una alerta que llega al usuario para recordarle que debe realizar una tarea.

**Comment by JJ** [comment]
Con este issue es difícil saber exactamente qué problema estás planteando, más allá de que haya un objeto o clase que se llame notificación. Trata de explicar un poco mejor qué es una notificación, y qué función cubre en la lógica de negocio.

**Comment by JJ** [comment]
Ahora has dicho que "es una alerta que le llega al usuario para hacer una tarea". Literalmente hace una explicación para cubrir el comentario que te he hecho. ¿Qué te parece que aporta esa frase a la resolución del problema en el código? Este es el código que has hecho con eso:

https://github.com/raultl12/organizacionSemanal/blob/8b1ea1aaa4f3c480850eab794af2e751e1b900e5/src/types.ts#L3

Hay 6 tareas. ¿En este issue explicas que el problema debe resolverse con 6 tipos de tareas? ¿Con tareas tipo "otros"? No acabo de entencer muy bien cómo se relaciona este issue con el código creado.
