### ISSUE TITLE
Representación de semana

### ISSUE THREAD

**Issue by raultl12** [carlotiii30/organizacionSemanal#9]
Para representar una semana según #2 debemos determinar que elementos la componen. Una semana debe de tener un conjunto de tareas a realizar por el usuario y las horas mínimas de actividad física y estudio que se desean realizar esa semana. ¿Cómo la representamos?

**Comment by JJ** [comment]
¿Sólo tiene actividad física?

**Comment by JJ** [comment]
Para que esto representara un problema, debería decirse al menos la razón por la que hay que representar esas actividades físicas, no asumir de antemano qué es lo que hay que representar. Si directamente se dice lo que hay que representar no se está planteando un problema sino una solución, que no va a corresponder a lo que desea el usuario.

**Comment by JJ** [comment]
Permíteme que te recuerde que no se puede cerrar ningún issue sin su commit. En entregas sucesivas le dará error a @carlotiii30 . La forma de proceder es, como te comenté, cerrar correctamente desde el PR o desde un commit fusionado en el mismo. Por favor, ábrelo y hazlo así. Borrarlo tampoco sería correcto, al menos en este caso, porque se perdería el comentario que se ha hecho, que conviene que se quede.
